# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Tatiana Anduquia
# Description of the Site
description: Data Scientist
# URL of Image of the Site
#site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Data Science, 
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.png
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage:  /assets/images/background_data_scientist_2.png #https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contacto@tatyandu.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: tatyandu
github_username:  Tatyandu
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Tatyandu

# Name of the Author
author-name: Tatiana Anduquia
# URL for the Image of the Author
author-image: /assets/images/perfil.png #https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Ingeniera de Sistemas con experiencia en desarrollo web y gestión de bases de datos. Después de varios años en la industria tecnológica, he decidido dar un giro a mi carrera hacia la Ciencia de Datos, un campo que me apasiona por su capacidad de extraer valor y conocimiento a partir de grandes volúmenes de datos. Aunque estoy iniciando en esta área, estoy entusiasmada por aprender y aplicar técnicas de análisis de datos y machine learning. Mi objetivo es desarrollar mi carrera como Científica de Datos en un entorno donde pueda combinar mi pasión por los datos con las habilidades técnicas que he adquirido a lo largo de mi trayectoria profesional.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Tatyandu

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
